version: '3.8'

services:
  crypto-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto-price-tracker
    ports:
      - "3000:80"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - crypto-network

networks:
  crypto-network:
    driver: bridge
